### ISSUE TITLE
scordbord無法正常顯示

### ISSUE THREAD

**Issue by LeZhk** [MCWonderland/WonderlandUHC#13]
**請問您的遊戲版本為？**
1.16.5

**請問您的 Java 版本為？ ([查看方式](https://pclevinblog.pixnet.net/blog/post/314562265-%5Bjava%5Djava%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E7%89%88%E6%9C%AC%E4%BD%8D%E5%85%83))**
請在此輸入版本，或是提供後台截圖
java 16

**請問 Bug 的內容是？**
scordbord無法正常顯示

**請問是怎麼觸發這個 Bug 的呢？**
不知道

**媒體提供**
![image](https://user-images.githubusercontent.com/87270699/185293583-0b130631-6e93-4d47-908c-51bfbb71c62e.png)

**Comment by lulu2002** [comment]
問題已經修復，記得下載最新版插件
