### ISSUE TITLE
POTION模式下可以跳躍

### ISSUE THREAD

**Issue by Hong4507** [MCWonderland/WonderlandUHC#16]
**請問您的遊戲版本為？**
1.8.8

**請問您的 Java 版本為？ ([查看方式](https://pclevinblog.pixnet.net/blog/post/314562265-%5Bjava%5Djava%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E7%89%88%E6%9C%AC%E4%BD%8D%E5%85%83))**
Java 17.5

**請問 Bug 的內容是？**
遊戲傳送完畢準備開始時，等待模式設定為POTION，玩家雖然無法左右移動，但是可以跳躍，而跳躍時也可以左右移動

**請問是怎麼觸發這個 Bug 的呢？**
點空白鍵

**媒體提供**
若是您方便，請在此提供上傳相關圖片或影片的連結，讓我能更快理解 Bug 發生的來龍去脈！

**Comment by lulu2002** [comment]
這個基本上無解XD 也是為什麼會出現 坐著 的模式之原因
