### ISSUE TITLE
右邊記分板不會顯示qqua

### ISSUE THREAD

**Issue by 712z** [MCWonderland/WonderlandUHC#4]
![2022-08-14_18 08 32](https://user-images.githubusercontent.com/111219024/184532138-10fed564-bf22-4ce1-b687-d57719158e2b.png)

**Comment by lulu2002** [comment]
嗨！這個從一開始就是這樣嗎？
從頭到尾完全沒有顯示計分板

**Comment by lulu2002** [comment]
後來驗證 是全程都看不到 先標註 Bug

**Comment by lulu2002** [comment]
1.0.2 已修正 (https://github.com/MCWonderland/WonderlandUHC/commit/9f11d0f816e64dcc30e00f4261b06a4fe49c4c90)
