### ISSUE TITLE
創造隊伍時不會有隊伍顏色

### ISSUE THREAD

**Issue by 712z** [MCWonderland/WonderlandUHC#9]
**請問您的遊戲版本為？**
伺服器是 1.16.5 ，裝了viaversion 。 MC本身是 1.17.1

**請問您的 Java 版本為？ ([查看方式](https://pclevinblog.pixnet.net/blog/post/314562265-%5Bjava%5Djava%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E7%89%88%E6%9C%AC%E4%BD%8D%E5%85%83))**
Java 16

**請問 Bug 的內容是？**
Random 跟 chosen 的時候都無法正常分隊(用的插件是最新的alpha-2_

**請問是怎麼觸發這個 Bug 的呢？**
/uhc splitteam 跟 Chosen 創造隊伍時都不會有隊伍顏色

**媒體提供**
![image](https://user-images.githubusercontent.com/111219024/184841082-d16d7eaf-56f0-41e2-8c6b-bd665ef0656c.png)

**Comment by lulu2002** [comment]
分隊問題跟 #2 衝突沒錯

這個 Issue 先改名

**Comment by lulu2002** [comment]
1.0.2 已修正
